INSERT INTO BeerType ([Name]) VALUES
('Lager'),
('Pilsner'),
('Pale Ale'),
('IPA (India Pale Ale)'),
('Stout'),
('Porter'),
('Blonde Ale'),
('Brown Ale'),
('Wheat Beer'),
('Saison'),
('Sour Ale'),
('Dubbel'),
('Tripel'),
('Quadrupel'),
('Barleywine'),
('Bock'),
('Doppelbock'),
('Helles'),
('Kölsch'),
('Schwarzbier'),
('Gose'),
('Lambic'),
('Gueuze'),
('Berliner Weisse'),
('American Amber Ale'),
('Belgian Strong Ale'),
('Scotch Ale'),
('Milk Stout'),
('Oatmeal Stout'),
('Irish Red Ale'),
('Altbier'),
('Rauchbier'),
('American Pale Ale'),
('American Brown Ale'),
('Imperial Stout'),
('New England IPA'),
('West Coast IPA'),
('Brut IPA'),
('Hazy IPA'),
('Fruit Beer'),
('Spiced Beer'),
('Pumpkin Ale'),
('Christmas Ale'),
('Cream Ale'),
('Märzen'),
('Vienna Lager'),
('Maibock'),
('Winter Warmer'),
('Belgian Dubbel'),
('Belgian Tripel'),
('Belgian Quadrupel'),
('Rye Beer'),
('Wild Ale'),
('Farmhouse Ale'),
('Flanders Red Ale'),
('California Common'),
('Steam Beer'),
('Old Ale'),
('Grisette'),
('Chilli Beer'),
('Herb and Spice Beer'),
('Smoked Beer'),
('Session Beer'),
('American Strong Ale'),
('English Strong Ale'),
('Fruit Lambic'),
('American Porter'),
('Imperial Porter'),
('Weizenbock'),
('Kristallweizen'),
('American Wild Ale');


INSERT INTO Countries ([Id], [Name], [CountryFlagUrl]) VALUES
(1, 'Afghanistan', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg'), 
(2, 'Albania', 'https://flagcdn.com/al.svg'), 
(3, 'Algeria', 'https://flagcdn.com/dz.svg'), 
(4, 'Andorra', 'https://flagcdn.com/ad.svg'), 
(5, 'Angola', 'https://flagcdn.com/ao.svg'), 
(6, 'Antigua and Barbuda', 'https://flagcdn.com/ag.svg'), 
(7, 'Argentina', 'https://flagcdn.com/ar.svg'), 
(8, 'Armenia', 'https://flagcdn.com/am.svg'), 
(9, 'Australia', 'https://flagcdn.com/au.svg'), 
(10, 'Austria', 'https://flagcdn.com/at.svg'), 
(11, 'Azerbaijan', 'https://flagcdn.com/az.svg'), 
(12, 'Bahamas', 'https://flagcdn.com/bs.svg'), 
(13, 'Bahrain', 'https://flagcdn.com/bh.svg'), 
(14, 'Bangladesh', 'https://flagcdn.com/bd.svg'), 
(15, 'Barbados', 'https://flagcdn.com/bb.svg'), 
(16, 'Belarus', 'https://flagcdn.com/by.svg'), 
(17, 'Belgium', 'https://flagcdn.com/be.svg'), 
(18, 'Belize', 'https://flagcdn.com/bz.svg'), 
(19, 'Benin', 'https://flagcdn.com/bj.svg'), 
(20, 'Bhutan', 'https://flagcdn.com/bt.svg'), 
(21, 'Bolivia', 'https://flagcdn.com/bo.svg'), 
(22, 'Bosnia and Herzegovina', 'https://flagcdn.com/ba.svg'), 
(23, 'Botswana', 'https://flagcdn.com/bw.svg'), 
(24, 'Brazil', 'https://flagcdn.com/br.svg'), 
(25, 'Brunei', 'https://flagcdn.com/bn.svg'), 
(26, 'Bulgaria', 'https://flagcdn.com/bg.svg'), 
(27, 'Burkina Faso', 'https://flagcdn.com/bf.svg'), 
(28, 'Burundi', 'https://flagcdn.com/bi.svg'), 
(29, 'Cabo Verde', 'https://flagcdn.com/cv.svg'), 
(30, 'Cambodia', 'https://flagcdn.com/kh.svg'), 
(31, 'Cameroon', 'https://flagcdn.com/cm.svg'), 
(32, 'Canada', 'https://flagcdn.com/ca.svg'), 
(33, 'Central African Republic', 'https://flagcdn.com/cf.svg'), 
(34, 'Chad', 'https://flagcdn.com/td.svg'), 
(35, 'Chile', 'https://flagcdn.com/cl.svg'), 
(36, 'China', 'https://flagcdn.com/tw.svg'), 
(37, 'Colombia', 'https://flagcdn.com/co.svg'), 
(38, 'Comoros', 'https://flagcdn.com/km.svg'), 
(39, 'Congo (Congo-Brazzaville)', 'https://flagcdn.com/cg.svg'), 
(40, 'Costa Rica', 'https://flagcdn.com/cr.svg'), 
(41, 'Croatia', 'https://flagcdn.com/hr.svg'), 
(42, 'Cuba', 'https://flagcdn.com/cu.svg'), 
(43, 'Cyprus', 'https://flagcdn.com/cy.svg'), 
(44, 'Czechia  (Czech Republic)', 'https://flagcdn.com/cz.svg'), 
(45, 'Denmark', 'https://flagcdn.com/dk.svg'), 
(46, 'Djibouti', 'https://flagcdn.com/dj.svg'), 
(47, 'Dominica', 'https://flagcdn.com/do.svg'), 
(48, 'Dominican Republic', 'https://flagcdn.com/do.svg'), 
(49, 'Ecuador', 'https://flagcdn.com/ec.svg'), 
(50, 'Egypt', 'https://flagcdn.com/eg.svg'), 
(51, 'El Salvador', 'https://flagcdn.com/sv.svg'), 
(52, 'Equatorial Guinea', 'https://flagcdn.com/gq.svg'), 
(53, 'Eritrea', 'https://flagcdn.com/er.svg'), 
(54, 'Estonia', 'https://flagcdn.com/ee.svg'), 
(55, 'Eswatini (fmr. "Swaziland")', 'https://flagcdn.com/sz.svg'), 
(56, 'Ethiopia', 'https://flagcdn.com/et.svg'), 
(57, 'Fiji', 'https://flagcdn.com/fj.svg'), 
(58, 'Finland', 'https://flagcdn.com/fi.svg'), 
(59, 'France', 'https://flagcdn.com/fr.svg'), 
(60, 'Gabon', 'https://flagcdn.com/ga.svg'), 
(61, 'Gambia', 'https://flagcdn.com/gm.svg'), 
(62, 'Georgia', 'https://flagcdn.com/gs.svg'), 
(63, 'Germany', 'https://flagcdn.com/de.svg'), 
(64, 'Ghana', 'https://flagcdn.com/gh.svg'), 
(65, 'Greece', 'https://flagcdn.com/gr.svg'), 
(66, 'Grenada', 'https://flagcdn.com/gd.svg'), 
(67, 'Guatemala', 'https://flagcdn.com/gt.svg'), 
(68, 'Guinea', 'https://flagcdn.com/gw.svg'), 
(69, 'Guinea-Bissau', 'https://flagcdn.com/gw.svg'), 
(70, 'Guyana', 'https://flagcdn.com/gy.svg'), 
(71, 'Haiti', 'https://flagcdn.com/ht.svg'), 
(72, 'Honduras', 'https://flagcdn.com/hn.svg'), 
(73, 'Hungary', 'https://flagcdn.com/hu.svg'), 
(74, 'Iceland', 'https://flagcdn.com/is.svg'), 
(75, 'India', 'https://flagcdn.com/in.svg'), 
(76, 'Indonesia', 'https://flagcdn.com/id.svg'), 
(77, 'Iran', 'https://flagcdn.com/ir.svg'), 
(78, 'Iraq', 'https://flagcdn.com/iq.svg'), 
(79, 'Ireland', 'https://flagcdn.com/gb.svg'), 
(80, 'Israel', 'https://flagcdn.com/il.svg'), 
(81, 'Italy', 'https://flagcdn.com/it.svg'), 
(82, 'Jamaica', 'https://flagcdn.com/jm.svg'), 
(83, 'Japan', 'https://flagcdn.com/jp.svg'), 
(84, 'Jordan', 'https://flagcdn.com/jo.svg'), 
(85, 'Kazakhstan', 'https://flagcdn.com/kz.svg'), 
(86, 'Kenya', 'https://flagcdn.com/ke.svg'), 
(87, 'Kiribati', 'https://flagcdn.com/ki.svg'), 
(88, 'Kuwait', 'https://flagcdn.com/kw.svg'), 
(89, 'Kyrgyzstan', 'https://flagcdn.com/kg.svg'), 
(90, 'Laos', 'https://flagcdn.com/la.svg'), 
(91, 'Latvia', 'https://flagcdn.com/lv.svg'), 
(92, 'Lebanon', 'https://flagcdn.com/lb.svg'), 
(93, 'Lesotho', 'https://flagcdn.com/ls.svg'), 
(94, 'Liberia', 'https://flagcdn.com/lr.svg'), 
(95, 'Libya', 'https://flagcdn.com/ly.svg'), 
(96, 'Liechtenstein', 'https://flagcdn.com/li.svg'), 
(97, 'Lithuania', 'https://flagcdn.com/lt.svg'), 
(98, 'Luxembourg', 'https://flagcdn.com/lu.svg'), 
(99, 'Madagascar', 'https://flagcdn.com/mg.svg'), 
(100, 'Malawi', 'https://flagcdn.com/mw.svg'), 
(101, 'Malaysia', 'https://flagcdn.com/my.svg'), 
(102, 'Maldives', 'https://flagcdn.com/mv.svg'), 
(103, 'Mali', 'https://flagcdn.com/ml.svg'), 
(104, 'Malta', 'https://flagcdn.com/mt.svg'), 
(105, 'Marshall Islands', 'https://flagcdn.com/mh.svg'), 
(106, 'Mauritania', 'https://flagcdn.com/mr.svg'), 
(107, 'Mauritius', 'https://flagcdn.com/mu.svg'), 
(108, 'Mexico', 'https://flagcdn.com/mx.svg'), 
(109, 'Micronesia', 'https://flagcdn.com/fm.svg'), 
(110, 'Moldova', 'https://flagcdn.com/md.svg'), 
(111, 'Monaco', 'https://flagcdn.com/mc.svg'), 
(112, 'Mongolia', 'https://flagcdn.com/mn.svg'), 
(113, 'Montenegro', 'https://flagcdn.com/me.svg'), 
(114, 'Morocco', 'https://flagcdn.com/ma.svg'), 
(115, 'Mozambique', 'https://flagcdn.com/mz.svg'), 
(116, 'Myanmar (formerly Burma)', 'https://flagcdn.com/mm.svg'), 
(117, 'Namibia', 'https://flagcdn.com/na.svg'), 
(118, 'Nauru', 'https://flagcdn.com/nr.svg'), 
(119, 'Nepal', 'https://flagcdn.com/np.svg'), 
(120, 'Netherlands', 'https://flagcdn.com/nl.svg'), 
(121, 'New Zealand', 'https://flagcdn.com/nz.svg'), 
(122, 'Nicaragua', 'https://flagcdn.com/ni.svg'), 
(123, 'Niger', 'https://flagcdn.com/ne.svg'), 
(124, 'Nigeria', 'https://flagcdn.com/ng.svg'), 
(125, 'North Korea', 'https://flagcdn.com/kp.svg'), 
(126, 'North Macedonia (formerly Macedonia)', 'https://flagcdn.com/mk.svg'), 
(127, 'Norway', 'https://flagcdn.com/no.svg'), 
(128, 'Oman', 'https://flagcdn.com/ro.svg'), 
(129, 'Pakistan', 'https://flagcdn.com/pk.svg'), 
(130, 'Palau', 'https://flagcdn.com/pw.svg'), 
(131, 'Palestine', 'https://flagcdn.com/ps.svg'), 
(132, 'Panama', 'https://flagcdn.com/pa.svg'), 
(133, 'Papua New Guinea', 'https://flagcdn.com/pg.svg'), 
(134, 'Paraguay', 'https://flagcdn.com/py.svg'), 
(135, 'Peru', 'https://flagcdn.com/pe.svg'), 
(136, 'Philippines', 'https://flagcdn.com/ph.svg'), 
(137, 'Poland', 'https://flagcdn.com/pl.svg'), 
(138, 'Portugal', 'https://flagcdn.com/pt.svg'), 
(139, 'Qatar', 'https://flagcdn.com/qa.svg'), 
(140, 'Romania', 'https://flagcdn.com/ro.svg'), 
(141, 'Russia', 'https://flagcdn.com/ru.svg'), 
(142, 'Rwanda', 'https://flagcdn.com/rw.svg'), 
(143, 'Saint Kitts and Nevis', 'https://flagcdn.com/kn.svg'), 
(144, 'Saint Lucia', 'https://flagcdn.com/lc.svg'), 
(145, 'Saint Vincent and the Grenadines', 'https://flagcdn.com/vc.svg'), 
(146, 'Samoa', 'https://flagcdn.com/as.svg'), 
(147, 'San Marino', 'https://flagcdn.com/sm.svg'), 
(148, 'Sao Tome and Principe', 'https://flagcdn.com/st.svg'), 
(149, 'Saudi Arabia', 'https://flagcdn.com/sa.svg'), 
(150, 'Senegal', 'https://flagcdn.com/sn.svg'), 
(151, 'Serbia', 'https://flagcdn.com/rs.svg'), 
(152, 'Seychelles', 'https://flagcdn.com/sc.svg'), 
(153, 'Sierra Leone', 'https://flagcdn.com/sl.svg'), 
(154, 'Singapore', 'https://flagcdn.com/sg.svg'), 
(155, 'Slovakia', 'https://flagcdn.com/sk.svg'), 
(156, 'Slovenia', 'https://flagcdn.com/si.svg'), 
(157, 'Solomon Islands', 'https://flagcdn.com/sb.svg'), 
(158, 'Somalia', 'https://flagcdn.com/so.svg'), 
(159, 'South Africa', 'https://flagcdn.com/za.svg'), 
(160, 'South Korea', 'https://flagcdn.com/kr.svg'), 
(161, 'South Sudan', 'https://flagcdn.com/ss.svg'), 
(162, 'Spain', 'https://flagcdn.com/es.svg'), 
(163, 'Sri Lanka', 'https://flagcdn.com/lk.svg'), 
(164, 'Sudan', 'https://flagcdn.com/sd.svg'), 
(165, 'Suriname', 'https://flagcdn.com/sr.svg'), 
(166, 'Sweden', 'https://flagcdn.com/se.svg'), 
(167, 'Switzerland', 'https://flagcdn.com/ch.svg'), 
(168, 'Syria', 'https://flagcdn.com/sy.svg'), 
(169, 'Taiwan', 'https://flagcdn.com/tw.svg'), 
(170, 'Tajikistan', 'https://flagcdn.com/tj.svg'), 
(171, 'Tanzania', 'https://flagcdn.com/tz.svg'), 
(172, 'Thailand', 'https://flagcdn.com/th.svg'), 
(173, 'Timor-Leste', 'https://flagcdn.com/tl.svg'), 
(174, 'Togo', 'https://flagcdn.com/tg.svg'), 
(175, 'Tonga', 'https://flagcdn.com/to.svg'), 
(176, 'Trinidad and Tobago', 'https://flagcdn.com/tt.svg'), 
(177, 'Tunisia', 'https://flagcdn.com/tn.svg'), 
(178, 'Turkey', 'https://flagcdn.com/tr.svg'), 
(179, 'Turkmenistan', 'https://flagcdn.com/tm.svg'), 
(180, 'Tuvalu', 'https://flagcdn.com/tv.svg'), 
(181, 'Uganda', 'https://flagcdn.com/ug.svg'), 
(182, 'Ukraine', 'https://flagcdn.com/ua.svg'), 
(183, 'United Arab Emirates', 'https://flagcdn.com/ae.svg'), 
(184, 'United Kingdom', 'https://flagcdn.com/gb.svg'), 
(185, 'United States of America', 'https://flagcdn.com/us.svg'), 
(186, 'Uruguay', 'https://flagcdn.com/uy.svg'), 
(187, 'Uzbekistan', 'https://flagcdn.com/uz.svg'), 
(188, 'Vanuatu', 'https://flagcdn.com/vu.svg'), 
(189, 'Venezuela', 'https://flagcdn.com/ve.svg'), 
(190, 'Vietnam', 'https://flagcdn.com/vn.svg'), 
(191, 'Yemen', 'https://flagcdn.com/ye.svg'), 
(192, 'Zambia', 'https://flagcdn.com/zm.svg'), 
(193, 'Zimbabwe', 'https://flagcdn.com/zw.svg');


INSERT INTO Breweries([Name], [CompleteADdress], [City], [IdCountry]) VALUES ('Test', 'Test', 'TEst', 1);

INSERT INTO Beers ([Name], [Description], [Price], [PictureUrl] , [Capacity], [AlcoholPercent], [IdBeerType], [IdBrewery], [Rating], [LikesTotal], [CreatedAt], [UpdatedAt], [BirthYear]) 
VALUES ('Jup','',1.2, 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg', 25, 5.2, 1, 1, 2.5, 0, GETDATE(),GETDATE(), 1964),
('Aa','',1.2, 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg' , 25, 5.2, 2, 1, 3, 0, GETDATE(),GETDATE(), 1988),
('Jup3','',1.2, 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg' , 25, 5.2, 3, 1, 1, 0, GETDATE(),GETDATE(), 1357),
('Cc','',1.2, 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg' , 25, 5.2, 4, 1, 4, 0, GETDATE(),GETDATE(), 1753);

INSERT INTO Cities ([Name], [CountryId]) VALUES ('Aalst', 17),
 ('Aarschot', 17),
 ('Andenne', 17),
 ('Antoing', 17),
 ('Antwerp', 17),
 ('Arlon', 17),
 ('Ath', 17),
 ('Aubange', 17),
 ('Bastogne', 17),
 ('Beaumont', 17),
 ('Beauraing', 17),
 ('Beringen', 17),
 ('Bilzen', 17),
 ('Binche', 17),
 ('Blankenberge', 17),
 ('Borgloon', 17),
 ('Bouillon', 17),
 ('Braine-le-Comte', 17),
 ('Bree', 17),
 ('Bruges', 17),
 ('Brussels', 17),
 ('Charleroi', 17),
 ('Châtelet', 17),
 ('Chièvres', 17),
 ('Chimay', 17),
 ('Chiny', 17),
 ('Ciney', 17),
 ('Comines-Warneton', 17),
 ('Couvin', 17),
 ('Damme', 17),
 ('Deinze', 17),
 ('Dendermonde', 17),
 ('Diest', 17),
 ('Diksmuide', 17),
 ('Dilsen-Stokkem', 17),
 ('Dinant', 17),
 ('Durbuy', 17),
 ('Eeklo', 17),
 ('Enghien', 17),
 ('Eupen', 17),
 ('Fleurus', 17),
 ('Florenville', 17),
 ('Fontaine-l''Évêque', 17),
 ('Fosses-la-Ville', 17),
 ('Geel', 17),
 ('Gembloux', 17),
 ('Genappe', 17),
 ('Genk', 17),
 ('Geraardsbergen', 17),
 ('Ghent', 17),
 ('Gistel', 17),
 ('Halen', 17),
 ('Halle', 17),
 ('Hamont-Achel', 17),
 ('Hannut', 17),
 ('Harelbeke', 17),
 ('Hasselt', 17),
 ('Herstal', 17),
 ('Huy', 17),
 ('Ixelles', 17),
 ('Jette', 17),
 ('Knokke-Heist', 17),
 ('Kortrijk', 17),
 ('La Louvière', 17),
 ('Leuven', 17),
 ('Liège', 17),
 ('Lokeren', 17),
 ('Louvain-la-Neuve', 17),
 ('Maaseik', 17),
 ('Malines', 17),
 ('Marche-en-Famenne', 17),
 ('Mons', 17),
 ('Mouscron', 17),
 ('Namur', 17),
 ('Nivelles', 17),
 ('Ostend', 17),
 ('Ottignies-Louvain-la-Neuve', 17),
 ('Roeselare', 17),
 ('Saint-Ghislain', 17),
 ('Seraing', 17),
 ('Sint-Niklaas', 17),
 ('Sint-Truiden', 17),
 ('Spa', 17),
 ('Tienen', 17),
 ('Tongeren', 17),
 ('Tournai', 17),
 ('Turnhout', 17),
 ('Verviers', 17),
 ('Vilvoorde', 17),
 ('Wavre', 17),
 ('Wervik', 17),
 ('Ypres', 17),
 ('Zottegem', 17);

INSERT INTO Addresses (IdCity, Street, PostCode, HouseNumber, CreatedAt, UpdatedAt) VALUES (22, 'Chemin du Sapin', '6000', '8', GETDATE(), GETDATE());

INSERT INTO Users 
([FirstName], [LastName],[NickName], [AccessToken],[RefreshToken],[IsActive],[IsAdmin],[UpdatedAt],[CreatedAt],[DateOfBirth],[Email],[PolicyCheck],[Password],[PictureUrl],[Phone], [AddressId])
VALUES ('Admin', 'test', 'Admin', '','',1,1, GETDATE(), GETDATE(), GETDATE(),'test@test.be', 1,'test','','',1);

INSERT INTO BeersRatings ([Comment], [CreatedAt], [UpdatedAt], [IdBeer], [IdUser], [Rate],[Likes]) VALUES
('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu sollicitudin nisl. Fusce porttitor ligula vitae lobortis congue. Nunc dapibus quis diam sed interdum. Vivamus egestas pulvinar rhoncus. Praesent fermentum tempus lectus, eget rutrum leo convallis sit amet. Pellentesque semper tellus tortor. Donec mauris libero, faucibus vitae lectus vel, vestibulum scelerisque dolor. Aliquam tristique nulla nec tellus congue, ac auctor enim dictum. Nam pellentesque felis vitae velit bibendum ultricies. Proin id lorem fermentum, mattis nibh sit amet, gravida nisi. Ut pulvinar dictum eros, et scelerisque ipsum congue a.', DATEADD(day, -10, GETDATE()), GETDATE(), 1 , 1, 2, 2),
('Lorem ipsum1 dolor sit amet, consectetur adipiscing elit. Maecenas eu sollicitudin nisl. Fusce porttitor ligula vitae lobortis congue. Nunc dapibus quis diam sed interdum. Vivamus egestas pulvinar rhoncus. Praesent fermentum tempus lectus, eget rutrum leo convallis sit amet. Pellentesque semper tellus tortor. Donec mauris libero, faucibus vitae lectus vel, vestibulum scelerisque dolor. Aliquam tristique nulla nec tellus congue, ac auctor enim dictum. Nam pellentesque felis vitae velit bibendum ultricies. Proin id lorem fermentum, mattis nibh sit amet, gravida nisi. Ut pulvinar dictum eros, et scelerisque ipsum congue a.', DATEADD(day, -5, GETDATE()), GETDATE(), 2 , 1, 3, 3),
('Lorem ipsum2 dolor sit amet, consectetur adipiscing elit. Maecenas eu sollicitudin nisl. Fusce porttitor ligula vitae lobortis congue. Nunc dapibus quis diam sed interdum. Vivamus egestas pulvinar rhoncus. Praesent fermentum tempus lectus, eget rutrum leo convallis sit amet. Pellentesque semper tellus tortor. Donec mauris libero, faucibus vitae lectus vel, vestibulum scelerisque dolor. Aliquam tristique nulla nec tellus congue, ac auctor enim dictum. Nam pellentesque felis vitae velit bibendum ultricies. Proin id lorem fermentum, mattis nibh sit amet, gravida nisi. Ut pulvinar dictum eros, et scelerisque ipsum congue a.', DATEADD(day, -2, GETDATE()), GETDATE(), 3 , 1, 1, 1),
('Lorem ipsum 3dolor sit amet, consectetur adipiscing elit. Maecenas eu sollicitudin nisl. Fusce porttitor ligula vitae lobortis congue. Nunc dapibus quis diam sed interdum. Vivamus egestas pulvinar rhoncus. Praesent fermentum tempus lectus, eget rutrum leo convallis sit amet. Pellentesque semper tellus tortor. Donec mauris libero, faucibus vitae lectus vel, vestibulum scelerisque dolor. Aliquam tristique nulla nec tellus congue, ac auctor enim dictum. Nam pellentesque felis vitae velit bibendum ultricies. Proin id lorem fermentum, mattis nibh sit amet, gravida nisi. Ut pulvinar dictum eros, et scelerisque ipsum congue a.', GETDATE(), GETDATE(), 4 , 1, 4, 0),
('Lorem ipsum1 dolor sit amet, consectetur adipiscing elit. Maecenas eu sollicitudin nisl. Fusce porttitor ligula vitae lobortis congue. Nunc dapibus quis diam sed interdum. Vivamus egestas pulvinar rhoncus. Praesent fermentum tempus lectus, eget rutrum leo convallis sit amet. Pellentesque semper tellus tortor. Donec mauris libero, faucibus vitae lectus vel, vestibulum scelerisque dolor. Aliquam tristique nulla nec tellus congue, ac auctor enim dictum. Nam pellentesque felis vitae velit bibendum ultricies. Proin id lorem fermentum, mattis nibh sit amet, gravida nisi. Ut pulvinar dictum eros, et scelerisque ipsum congue a.', DATEADD(day, -5, GETDATE()), GETDATE(), 1 , 1, 3, 3),
('Lorem ipsum2 dolor sit amet, consectetur adipiscing elit. Maecenas eu sollicitudin nisl. Fusce porttitor ligula vitae lobortis congue. Nunc dapibus quis diam sed interdum. Vivamus egestas pulvinar rhoncus. Praesent fermentum tempus lectus, eget rutrum leo convallis sit amet. Pellentesque semper tellus tortor. Donec mauris libero, faucibus vitae lectus vel, vestibulum scelerisque dolor. Aliquam tristique nulla nec tellus congue, ac auctor enim dictum. Nam pellentesque felis vitae velit bibendum ultricies. Proin id lorem fermentum, mattis nibh sit amet, gravida nisi. Ut pulvinar dictum eros, et scelerisque ipsum congue a.', DATEADD(day, -2, GETDATE()), GETDATE(), 1 , 1, 1, 1),
('Lorem ipsum 3dolor sit amet, consectetur adipiscing elit. Maecenas eu sollicitudin nisl. Fusce porttitor ligula vitae lobortis congue. Nunc dapibus quis diam sed interdum. Vivamus egestas pulvinar rhoncus. Praesent fermentum tempus lectus, eget rutrum leo convallis sit amet. Pellentesque semper tellus tortor. Donec mauris libero, faucibus vitae lectus vel, vestibulum scelerisque dolor. Aliquam tristique nulla nec tellus congue, ac auctor enim dictum. Nam pellentesque felis vitae velit bibendum ultricies. Proin id lorem fermentum, mattis nibh sit amet, gravida nisi. Ut pulvinar dictum eros, et scelerisque ipsum congue a.', GETDATE(), GETDATE(), 1, 1, 4, 0);

INSERT INTO LikesRating
    ([Liked], [IdUser], [IdRating]) VALUES (1,1,1);